CREATE TABLE "GCG_5878_SUPP_PERF" (
 "TERMINAL" CHAR(3),
 "VENDOR_NAME" CHAR(50),
 "ON_TIME_PERF" DOUBLE,
 "QA_PERF" DOUBLE,
 "EASE_OF_BUSINESS" DOUBLE,
 "OVERALL_PERF" DOUBLE,
 "VENDOR_STATUS" CHAR(50),
 "RECEIPTS" INTEGER,
 "ON_TIME" DOUBLE,
 "LATE" DOUBLE,
 "ITEMS_ACCEPTED" INTEGER,
 "ITEMS_REJECTED" INTEGER );